test:
  _target_: src.datasets.CustomDirAudioDataset
  audio_dir: custom_dataset/audio
  transcription_dir: custom_dataset/transcriptions
  instance_transforms: ${transforms.instance_transforms.inference}