custom:
  _target_: src.datasets.CustomDirAudioDataset
  audio_dir: data/datasets/librispeech/custom/audio
  transcription_dir: data/datasets/librispeech/custom/transcriptions
  instance_transforms: ${transforms.instance_transforms.inference}