train:
  data_object:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.Normalize1D
        mean: 0.5
        std: 0.5
inference:
  data_object:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.Normalize1D
        mean: 0.5
        std: 0.5
