defaults:
  - model: conformer
  - metrics: metrics
  - datasets: test-other
  - dataloader: torch_dataloader
  - transforms: only_instanse
  - text_encoder: ctc
  - _self_
inferencer:
  device_tensors: ["data_object", "labels"]
  device: auto
  save_path: "inference_saved"
  seed: 1
  from_pretrained: "saved/model_best.pth"
