defaults:
  - model: conformer
  - writer: cometml
  - metrics: metrics
  - datasets: train-clean-100
  - dataloader: torch_dataloader
  - transforms: only_instanse
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 1e-3
  pct_start: 0.1
  steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos
loss_function:
  _target_: src.loss.CTCLossWrapper
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
trainer:
  detect_anomaly: false
  log_step: 50
  n_epochs: 20
  epoch_len: 400
  device_tensors: ["spectrogram", "text_encoded"]
  resume_from: null
  device: auto
  override: True
  max_grad_norm: 5.0
  monitor: "min val_WER_(Argmax)"
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
